IF
	Global("KTQuest","%FriendlyArmInn%",0)
THEN
	RESPONSE #100
		CreateCreature("ktmonk01",[1316.2194],12)
		CreateCreature("ktmonk02",[1309.2272],12)
		CreateCreature("ktmonk02",[1382.2138],12)
		SetGlobal("KTQuest","%FriendlyArmInn%",1)
END

IF
	PartyHasItem("KTRedB")
	Global("KTRedB","%FriendlyArmInn%",0)
THEN
	RESPONSE #100
		SetGlobal("KTRedB","%FriendlyArmInn%",1)
		SetGlobal("KTQuest","%FriendlyArmInn%",4)
END
